### ISSUE TITLE
How to Convert MS Word Equation into Markdown LaTex Equation

### ISSUE THREAD

**Issue by riven314** [fastai/fast_template#30]
Thanks for the amazing work that make blogging so easy. 

I am trying to make my first (testing) post with Microsoft Word. The attached is what I wrote in the Word file:

![equ](https://user-images.githubusercontent.com/21143399/75625200-b251a900-5bf6-11ea-9d26-19dc510230e5.JPG)

But I found that pandoc didn't convert it to Markdown LaTex equation. The attached is what is shown in the blog:

![equ2](https://user-images.githubusercontent.com/21143399/75625216-e7f69200-5bf6-11ea-806f-95e3aa1130e5.JPG)

Just wonder if there is a solution/ walkaround for this?

**Comment by hamelsmu** [comment]
Please ask this on the fastai forums 
https://forums.fast.ai/c/fastai-users/nbdev/

**Comment by riven314** [comment]
ok! thanks anyway

**Comment by hamelsmu** [comment]
No problem, its just that you are likely to get more help there.  I don't know the answer to this question [yet], so its better for visibility!
