### ISSUE TITLE
After modifying the two-level title of the first line of the about.md file, the link "about" in the navigation disappears

### ISSUE THREAD

**Issue by pf-z** [fastai/fast_template#8]
When modifying the first line of the about.md file(as follows):
```
# About
```
Modified to

```
# About me
```

the link "about" in the navigation disappears.

If you revise `#About me` in `about.md` to `#About`, then the link "about" in the navigation will appear.

**Comment by jph00** [comment]
Thanks for the issue. The best place for this is at the repo for the template responsible: https://github.com/jekyll/minima
